T = {
  "cancel": "Cancelar", "save": "Guardar", "saved": "Guardado", "delete": "Eliminar", "edit": "Editar",
  "next": "Siguiente", "retry": "Reintentar", "yes": "Sí", "no": "No", "you": "tú",
  "required": "Obligatorio", "open": "Abrir", "install": "Instalar", "leave": "Salir",
  "accept": "Aceptar", "reject": "Rechazar", "confirmAction": "Confirmar",
  "errDeviceInUse": "Este teléfono ya está vinculado a otra cuenta de TestPact. Una cuenta por dispositivo mantiene los grupos justos.",
  "errBanned": "Tu cuenta no puede unirse a nuevos grupos por ahora. Puedes enviar una apelación.",
  "errAlreadyInGroup": "Ya estás en un grupo. Termínalo primero.",
  "errAppNotFound": "Esa app ya no existe.",
  "errAppealOpen": "Ya tienes una apelación pendiente de revisión.",
  "errAlreadyRated": "Ya calificaste este comentario.",
  "errIntegrity": "Este dispositivo no pasó la verificación de integridad de Google Play. Usa un teléfono real con la app instalada desde Google Play.",
  "errNetwork": "Sin conexión. Revisa tu internet e inténtalo de nuevo.",
  "errGeneric": "Algo salió mal. Inténtalo de nuevo.",
  "levelProbation": "En prueba", "levelNewcomer": "Recién llegado", "levelMember": "Miembro", "levelTrusted": "De confianza", "levelTopTester": "Top tester",
  "reasonNotInstalled": "No instaló mi app", "reasonUninstalled": "La desinstaló durante la prueba",
  "reasonNotOpening": "No abre las apps cada día", "reasonEmailNotAdded": "No añadió mi correo a su prueba",
  "reasonSpam": "Spam o abuso", "reasonFakeFeedback": "Comentarios falsos o copiados", "reasonOther": "Otro",
  "catBug": "Error", "catUx": "Diseño / UX", "catIdea": "Idea", "catPraise": "Elogio", "catOther": "Otro",
  "badgeFirstPact": "Primer pacto", "badgeVeteran": "Veterano (5 grupos)", "badgePerfect": "Racha perfecta",
  "badgeHelpful": "Revisor útil", "badgeTopTester": "Top tester",
  "removedSetup": "no completó la configuración a tiempo", "removedInactive": "inactivo durante 3 días",
  "removedReported": "reportes confirmados por el admin", "removedLeft": "salió del grupo",
  "removedCancelled": "grupo cancelado", "removedEnded": "grupo finalizado", "removedOther": "eliminado",
  "trustAdmin": "Ajuste del admin: {reason}",
  "trustGroupCompleted": "Completó un grupo", "trustActiveDay": "Abrió todas las apps del día",
  "trustMissedDay": "Faltó un día", "trustHelpfulFeedback": "Comentario marcado como útil",
  "trustKickedInactive": "Eliminado por inactividad", "trustKickedReported": "Eliminado tras reportes confirmados",
  "trustSetupFailed": "Configuración sin terminar", "trustLeftGroup": "Salió antes de un grupo",
  "trustFalseReport": "Reporte rechazado por el admin", "trustAppealAccepted": "Apelación aceptada",
  "statusSetup": "Configuración", "statusActive": "En prueba", "statusCompleted": "Completado", "statusCancelled": "Cancelado",
  "stateSetup": "Configurando", "stateActive": "Probando", "stateSuspended": "En revisión", "stateRemoved": "Eliminado", "stateCompleted": "Completado",
  "language": "Idioma", "tagline": "Testers reales. Comentarios reales.\nSupera juntos las pruebas cerradas de Google Play.",
  "signInBullet1": "Únete a un grupo de hasta 20 desarrolladores Android",
  "signInBullet2": "Las instalaciones y el uso diario se verifican en el dispositivo",
  "signInBullet3": "Da y recibe comentarios honestos que mejoran tu app",
  "continueWithGoogle": "Continuar con Google", "privacyPolicy": "Política de privacidad", "terms": "Términos",
  "ob1Title": "Un pacto entre desarrolladores",
  "ob1P1": "Google exige 12 testers inscritos durante 14 días antes de que una cuenta personal nueva pase a producción.",
  "ob1P2": "Te unes a un grupo. Todos se añaden como testers y todos instalan las apps de todos.",
  "ob1P3": "Durante 16 días abres cada app de tu lista a diario. Los demás hacen lo mismo con la tuya.",
  "ob2Title": "Justo para todos",
  "ob2P1": "Tu app solo se muestra a los demás después de que añades sus correos: primero das, luego recibes.",
  "ob2P2": "Tu puntuación de confianza sube cuando pruebas a diario y das comentarios útiles, y baja cuando no.",
  "ob2P3": "Los miembros inactivos reciben avisos y se eliminan tras 3 días sin actividad. Los reportes se contrastan con datos de uso reales.",
  "ob3Title": "Demuestra tus pruebas automáticamente",
  "ob3P1": "TestPact solo revisa las apps que te asignaron: si están instaladas y cuántos minutos las usaste hoy.",
  "ob3P2": "Nunca se lee ni se envía nada sobre tus otras apps.",
  "usageAccessTitle": "Acceso a uso",
  "usageAccessBody": "Permite a TestPact contar los minutos que pasas en tus apps asignadas, así recibes crédito aunque las abras desde la pantalla de inicio.",
  "granted": "Concedido ✓", "notGranted": "No concedido, toca para activarlo", "grantUsageAccess": "Conceder acceso a uso",
  "notificationsTitle": "Recordatorios", "notificationsBody": "Recordatorios diarios y novedades del grupo para que nunca te saltes un día.",
  "allowNotifications": "Permitir notificaciones", "getStarted": "Empezar", "settingUp": "Preparando tu cuenta…",
  "signOut": "Cerrar sesión", "tabHome": "Inicio", "tabMyApps": "Mis apps", "tabFeedback": "Comentarios", "tabProfile": "Perfil",
  "admin": "Admin", "settings": "Ajustes", "addApp": "Añadir app",
  "bannedTitle": "Cuenta restringida",
  "bannedBody": "Tienes {count} faltas, así que no puedes unirte a nuevos grupos. Si crees que es un error, envía una apelación.",
  "appeal": "Apelar",
  "strikesTitle": "{count, plural, =1{1 falta} other{{count} faltas}} en tu cuenta",
  "strikesBody": "Con 3 faltas no puedes unirte a nuevos grupos. Las faltas vienen de expulsiones por inactividad o reportes confirmados.",
  "howItWorks": "Cómo funciona",
  "googleRuleTitle": "La regla de Google Play",
  "googleRuleBody": "Las cuentas personales de desarrollador creadas después del 13 de noviembre de 2023 necesitan al menos 12 testers inscritos durante 14 días seguidos. Los grupos empiezan con 20 personas y duran 16 días, así tienes margen. Google también comprueba que los testers usaron de verdad la app: no basta con instalarla, ábrela y explórala.",
  "hello": "Hola, {name} 👋",
  "joinCardTitle": "¿Listo para encontrar testers?",
  "joinCardBody": "Únete a la cola. En cuanto haya suficientes desarrolladores, tu grupo se crea automáticamente.",
  "joinCardNoApps": "Primero añade la app que quieres probar, con su enlace de prueba cerrada.",
  "joinGroup": "Unirse a un grupo", "addYourApp": "Añade tu app",
  "inQueueTitle": "Estás en la cola",
  "inQueueBody": "Esperando para incluir {app} en un grupo {tier}. Te avisaremos cuando esté listo.",
  "tierTrusted": "de confianza", "tierStarter": "inicial",
  "queueWaiting": "{count} de {size} desarrolladores esperando", "queueJoinedAt": "Te uniste el {time}", "leaveQueue": "Salir de la cola",
  "dayOf": "Día {day} de {total}", "groupTitle": "Grupo #{id}",
  "openedToday": "Abiertas hoy: {opened} de {total}",
  "setupDoneWaiting": "Configuración lista ✓ Esperando a que terminen los demás.",
  "setupTodo": "Termina la configuración: añade los correos e instala las apps de todos.",
  "suspendedBody": "Estás en revisión tras varios reportes. Un admin está revisando tus datos de actividad.",
  "openGroup": "Abrir grupo",
  "step1Title": "Añade tu app", "step1Body": "Nombre, paquete y tu enlace de inscripción a la prueba cerrada.",
  "step2Title": "Únete a la cola", "step2Body": "Los grupos de 20 se forman solos. Los testers de confianza se agrupan entre sí.",
  "step3Title": "Configura en 48 h", "step3Body": "Pega los correos de todos en Play Console y luego únete e instala cada app.",
  "step4Title": "Prueba a diario durante 16 días", "step4Body": "Abre cada app todos los días y deja comentarios reales. Lo verificamos en el dispositivo.",
  "step5Title": "Solicita producción", "step5Body": "Gana puntos de confianza e insignias y solicita el acceso a producción en Play Console.",
  "rule1": "Añadiré el correo de cada miembro a mi prueba cerrada en 48 horas.",
  "rule2": "Instalaré la app de cada miembro y la mantendré hasta el final.",
  "rule3": "Abriré cada app a diario durante 16 días y daré comentarios honestos.",
  "rule4": "Entiendo que los miembros inactivos son eliminados y pierden puntos de confianza.",
  "chooseApp": "¿Qué app quieres que prueben?", "yourCommitment": "Tu compromiso",
  "joinedQueue": "¡Estás en la cola!", "joinQueue": "Unirse a la cola",
  "noAppsTitle": "Aún no hay apps", "noAppsBody": "Añade la app que quieres probar. Necesitarás su enlace de inscripción a la prueba cerrada de Play Console.",
  "deleteAppTitle": "¿Eliminar esta app?", "deleteAppBody": "Los grupos que ya la incluyen conservan su copia. Puedes volver a añadirla luego.",
  "editApp": "Editar app", "appIcon": "Toca para elegir el ícono", "appName": "Nombre de la app", "packageName": "Nombre del paquete",
  "invalidPackage": "Introduce un paquete válido, p. ej. com.example.app",
  "optInLink": "Enlace de inscripción a la prueba cerrada",
  "optInHelp": "Play Console → Testing → Closed testing → Testers → enlace \"Join on the web\".",
  "invalidOptIn": "Debe ser un enlace play.google.com/apps/testing/…",
  "shortDescription": "Descripción corta", "testNotes": "¿Qué deberían probar?",
  "testNotesHelp": "p. ej. \"Crea una cuenta y añade 2 productos al carrito\". Los testers lo verán cada día.",
  "closedTestTipTitle": "Antes de unirte",
  "closedTestTipBody": "Crea un canal de prueba cerrada, sube una versión, publícala y configura los testers como lista de correos. Los correos de tu grupo van ahí.",
  "tabToday": "Hoy", "tabSetup": "Configuración", "tabMembers": "Miembros", "tabActivity": "Actividad",
  "leaveGroup": "Salir del grupo", "leaveGroupTitle": "¿Salir de este grupo?",
  "leaveGroupBody": "Los demás dejarán de probar tu app y perderás puntos de confianza. No se puede deshacer.",
  "youWereRemoved": "Fuiste eliminado: {reason}.",
  "youCompleted": "Completaste este grupo 🏆 Ya puedes solicitar el acceso a producción en Play Console.",
  "setupDeadlinePassed": "Venció el plazo de configuración. Procesando…",
  "setupTimeLeft": "Quedan {hours} h {minutes} min para terminar la configuración",
  "setupExplain": "Quien no termine será reemplazado desde la cola. La prueba empieza cuando todos están listos.",
  "step1AddEmails": "Paso 1 · Añade testers a tu prueba cerrada",
  "addEmailsBody": "Copia los {count} correos y pégalos en la lista de correos de tu prueba cerrada en Play Console.",
  "copyAllEmails": "Copiar todos los correos", "copied": "{count} correos copiados",
  "emailsConfirmed": "Correos añadidos", "iAddedEveryone": "Añadí a todos",
  "confirmEmailsTitle": "¿Añadiste todos los correos?",
  "confirmEmailsBody": "Confirma que los {count} correos están en la lista de testers de tu prueba cerrada y que guardaste el cambio. Los miembros pueden reportarte si no pueden unirse.",
  "yesAdded": "Sí, todos añadidos",
  "emailsHowTo": "Play Console → tu app → Testing → Closed testing → Testers → Email list → pegar → Save.",
  "step2InstallApps": "Paso 2 · Únete e instala las apps ({done}/{total})",
  "checkAgain": "Comprobar de nuevo",
  "waitingForOwners": "{count, plural, =1{1 miembro aún no ha} other{{count} miembros aún no han}} añadido los correos del grupo. Sus apps aparecerán aquí cuando lo hagan.",
  "noAppsYet": "Aún no hay apps para instalar.", "byName": "de {name}", "joinTest": "Unirse a la prueba",
  "newMembersTitle": "Se unió un nuevo miembro",
  "newMembersBody": "Añade los nuevos correos a tu prueba cerrada e instala su app. Abre la pestaña Configuración.",
  "usageAccessOffTitle": "El acceso a uso está desactivado",
  "usageAccessOffBody": "Solo cuentan las apps que abres con el botón Abrir. Activa el acceso a uso para recibir crédito también al abrirlas desde la pantalla de inicio.",
  "yourTestList": "Tu lista de pruebas",
  "todayTitle": "Pruebas de hoy", "todayDone": "¡Todo listo por hoy! 🎉", "todayDoneBody": "Buen trabajo. Vuelve mañana.",
  "todayBody": "Abre al menos {needed} apps y usa cada una un rato.",
  "dayResetsAt": "El nuevo día empieza a las {time}",
  "notInstalled": "No instalada", "openedMinutes": "Abierta hoy · {minutes} min", "notOpenedYet": "No abierta hoy",
  "feedbackGivenCount": "Comentarios ({count})", "giveFeedback": "Comentar",
  "statMembers": "Miembros", "statOnTrack": "Al día hoy", "statRemoved": "Eliminados",
  "membersLegend": "🟢 al día  🟡 pendiente  🔴 días perdidos  ⚪ salió",
  "memberSetupLine": "correos {emails} · instaladas {installed}/{total}",
  "memberActiveLine": "instaladas {installed}/{total} · abiertas {opened}/{total} · comentarios {feedback}",
  "missedInARow": "{count} día(s) seguidos sin actividad",
  "lastDays": "Últimos días", "viewProfile": "Ver perfil", "openInPlay": "Abrir en Play Store", "reportMember": "Reportar",
  "reportSent": "Reporte enviado. Gracias por mantener los grupos justos.",
  "reportTitle": "Reportar a {name}",
  "reportExplain": "Solo se actúa cuando varios miembros reportan Y nuestros datos de uso coinciden. Los reportes falsos cuestan puntos de confianza.",
  "detailsOptional": "Detalles (opcional)", "addScreenshot": "Añadir captura", "screenshotAdded": "Captura añadida ✓",
  "sendReport": "Enviar reporte", "noActivity": "Aún no hay actividad",
  "evFormed": "Grupo formado con {count} desarrolladores", "evJoined": "{name} se unió al grupo",
  "evEmailsAdded": "{name} añadió los correos de todos", "evStarted": "Comenzó la prueba: día 1",
  "evMemberActive": "{name} terminó la configuración y empezó a probar", "evWarning": "{name} faltó 2 días seguidos (último aviso)",
  "evRemoved": "{name} fue eliminado ({reason})", "evSuspended": "{name} está en revisión del admin",
  "evReinstated": "{name} fue absuelto y volvió", "evCompleted": "Grupo completado 🏆", "evCancelled": "Grupo cancelado",
  "feedbackSent": "Comentario enviado. ¡Gracias!", "feedbackFor": "Comentarios: {app}",
  "developerAsks": "El desarrollador te pide probar", "rating": "Valoración", "category": "Categoría",
  "yourFeedback": "Tu comentario",
  "feedbackHint": "¿Qué funcionó, qué falló, qué te confundió? Sé específico: pantallas, pasos, dispositivo.",
  "feedbackMin": "Al menos 20 caracteres", "sendFeedback": "Enviar comentario",
  "received": "Recibidos", "given": "Enviados",
  "noFeedbackReceived": "Aún no hay comentarios", "noFeedbackReceivedBody": "Aquí verás los comentarios de los testers de tu grupo.",
  "noFeedbackGiven": "Aún no has dado comentarios", "noFeedbackGivenBody": "Usa el botón Comentar en cada app de la pestaña Hoy de tu grupo.",
  "fromOnApp": "{name} sobre {app}", "wasHelpful": "¿Te fue útil?",
  "markedHelpful": "Lo marcaste como útil (+2 de confianza para esa persona)", "markedNotHelpful": "Marcado como no útil",
  "groupHistory": "Grupos", "noGroupsYet": "Aún no hay grupos.",
  "trustHistory": "Historial de confianza", "noTrustHistory": "Aún no hay cambios.",
  "trustScore": "Puntuación de confianza", "pointsToNext": "{points} puntos para el siguiente nivel",
  "statCompleted": "Grupos completados", "statCompletionRate": "Tasa de finalización", "statDailyActivity": "Actividad diaria",
  "statActiveDays": "Días activos", "statFeedback": "Comentarios dados", "statHelpful": "Comentarios útiles",
  "badges": "Insignias", "noBadges": "Completa tu primer grupo para ganar una insignia.",
  "systemLanguage": "Predeterminado del sistema", "general": "General", "about": "Acerca de",
  "contactSupport": "Contactar soporte", "rateApp": "Valorar TestPact", "account": "Cuenta",
  "deleteAccount": "Eliminar cuenta", "deleteAccountTitle": "¿Eliminar tu cuenta?",
  "deleteAccountBody": "Tu perfil, apps y puntuación de confianza se eliminarán para siempre. Si estás en un grupo, saldrás de él.",
  "appealTitle": "Apelar una decisión",
  "appealExplain": "Explica qué pasó. Un admin revisa cada apelación. Si se acepta, se quita una falta y recuperas algunos puntos de confianza.",
  "appealHint": "¿Qué pasó? Incluye fechas y cualquier dato que nos ayude a comprobarlo.",
  "appealSent": "Apelación enviada", "sendAppeal": "Enviar apelación", "yourAppeals": "Tus apelaciones",
  "appealOpen": "Pendiente de revisión", "appealAccepted": "Aceptada", "appealRejected": "Rechazada",
  "adminReviews": "Revisiones", "adminAppeals": "Apelaciones", "adminUsers": "Usuarios",
  "noteOptional": "Nota para el usuario (opcional)", "nothingToReview": "Nada que revisar 🎉",
  "dataSummary": "Datos de uso: {active} días activos, {missed} días perdidos",
  "rejectReports": "Rechazar reportes", "confirmKick": "Confirmar y eliminar",
  "searchByEmail": "Buscar usuario por correo", "userNotFound": "No hay usuarios con ese correo.",
  "userSummary": "Confianza {trust} · faltas {strikes} · bloqueado: {banned}",
  "ban": "Bloquear", "unban": "Desbloquear", "adjustTrust": "Ajustar confianza",

  "notificationsInbox": "Notificaciones", "markAllRead": "Marcar todo como leído",
  "noNotifications": "Aún no hay notificaciones",
  "noNotificationsBody": "Aquí verás novedades del grupo, recordatorios, avisos y alertas de comentarios.",
  "notificationSettings": "Notificaciones",
  "notifPermissionOff": "Las notificaciones de TestPact están desactivadas", "openSettings": "Abrir ajustes",
  "notifDaily": "Recordatorios diarios",
  "notifDailySub": "Aviso por la tarde si aún no abriste las apps de hoy, y plazos de configuración",
  "notifGroup": "Novedades del grupo", "notifGroupSub": "Grupo formado, prueba iniciada, nuevos miembros, finalización",
  "notifFeedback": "Comentarios", "notifFeedbackSub": "Cuando alguien deja comentarios sobre tu app",
  "notifImportantNote": "Los avisos y expulsiones siempre se envían, para que no te pierdas nada que afecte a tu lugar.",
  "noInternetTitle": "Sin conexión a internet",
  "noInternetBody": "Revisa tu Wi-Fi o datos móviles. TestPact se reconecta automáticamente en cuanto vuelvas a estar en línea.",
  "checkingConnection": "Comprobando…", "backOnline": "De nuevo en línea",
  "updateRequiredTitle": "Actualización necesaria",
  "updateRequiredBody": "Esta versión de TestPact ya no es compatible. Actualiza para seguir probando con tu grupo.",
  "updateAvailableTitle": "Actualización disponible",
  "updateAvailableBody": "Hay una nueva versión de TestPact con mejoras y correcciones.",
  "updateNow": "Actualizar ahora", "later": "Más tarde",
  "updateDownloaded": "Actualización descargada. Reinicia para terminar de instalarla.", "restart": "Reiniciar",
  "appVersion": "Versión {version}",

  "welcomeBack": "¡Qué bueno verte de nuevo!", "viewAll": "Ver todo", "more": "Más",
  "filterAll": "Todas", "statusTesting": "En prueba", "inQueueShort": "En cola", "statusReady": "Lista",
  "memberDone": "Listo", "memberTesting": "Probando", "memberPending": "Pendiente",
  "todaysTasks": "Tareas de hoy",
  "tasksCompleted": "{total} apps · {done}/{total} completadas",
  "groupMembersCount": "Miembros del grupo ({count})",
  "recentActivity": "Actividad reciente",
  "badgesEarned": "{earned} de {total} conseguidas",
}
