T = {
  "cancel": "રદ કરો", "save": "સેવ કરો", "saved": "સેવ થયું", "delete": "કાઢી નાખો", "edit": "બદલો",
  "next": "આગળ", "retry": "ફરી પ્રયાસ કરો", "yes": "હા", "no": "ના", "you": "તમે",
  "required": "જરૂરી છે", "open": "ખોલો", "install": "ઇન્સ્ટોલ કરો", "leave": "છોડો",
  "accept": "સ્વીકારો", "reject": "નકારો", "confirmAction": "પુષ્ટિ કરો",
  "errDeviceInUse": "આ ફોન પહેલેથી બીજા TestPact એકાઉન્ટ સાથે જોડાયેલો છે. દરેક ડિવાઇસ પર એક એકાઉન્ટથી ગ્રુપ ન્યાયી રહે છે.",
  "errBanned": "હાલમાં તમારું એકાઉન્ટ નવા ગ્રુપમાં જોડાઈ શકતું નથી. તમે અપીલ મોકલી શકો છો.",
  "errAlreadyInGroup": "તમે પહેલેથી એક ગ્રુપમાં છો. પહેલા તે પૂરું કરો.",
  "errAppNotFound": "આ એપ લિસ્ટિંગ હવે અસ્તિત્વમાં નથી.",
  "errAppealOpen": "તમારી એક અપીલ પહેલેથી સમીક્ષા માટે બાકી છે.",
  "errAlreadyRated": "તમે આ ફીડબેકને પહેલેથી રેટ કર્યો છે.",
  "errIntegrity": "આ ડિવાઇસ Google Play ની ઇન્ટિગ્રિટી તપાસમાં પાસ ન થયું. Google Play પરથી ઇન્સ્ટોલ કરેલી એપ સાથે અસલી ફોન વાપરો.",
  "errNetwork": "કનેક્શન નથી. ઇન્ટરનેટ તપાસો અને ફરી પ્રયાસ કરો.",
  "errGeneric": "કંઈક ખોટું થયું. કૃપા કરી ફરી પ્રયાસ કરો.",
  "levelProbation": "પ્રોબેશન", "levelNewcomer": "નવા સભ્ય", "levelMember": "સભ્ય", "levelTrusted": "વિશ્વસનીય", "levelTopTester": "ટોપ ટેસ્ટર",
  "reasonNotInstalled": "મારી એપ ઇન્સ્ટોલ ન કરી", "reasonUninstalled": "ટેસ્ટ દરમિયાન અનઇન્સ્ટોલ કરી",
  "reasonNotOpening": "રોજ એપ્સ ખોલતા નથી", "reasonEmailNotAdded": "મારો ઈમેલ તેમના ટેસ્ટમાં ન ઉમેર્યો",
  "reasonSpam": "સ્પામ અથવા દુર્વ્યવહાર", "reasonFakeFeedback": "નકલી અથવા કોપી-પેસ્ટ ફીડબેક", "reasonOther": "અન્ય",
  "catBug": "બગ", "catUx": "ડિઝાઇન / UX", "catIdea": "સૂચન", "catPraise": "વખાણ", "catOther": "અન્ય",
  "badgeFirstPact": "પહેલો પેક્ટ", "badgeVeteran": "અનુભવી (5 ગ્રુપ)", "badgePerfect": "પરફેક્ટ સ્ટ્રીક",
  "badgeHelpful": "મદદરૂપ સમીક્ષક", "badgeTopTester": "ટોપ ટેસ્ટર",
  "removedSetup": "સેટઅપ સમયસર પૂરું ન થયું", "removedInactive": "3 દિવસથી નિષ્ક્રિય",
  "removedReported": "એડમિને ફરિયાદની પુષ્ટિ કરી", "removedLeft": "ગ્રુપ છોડી દીધું",
  "removedCancelled": "ગ્રુપ રદ થયું", "removedEnded": "ગ્રુપ પૂરું થયું", "removedOther": "દૂર કરાયા",
  "trustAdmin": "એડમિન દ્વારા ફેરફાર: {reason}",
  "trustGroupCompleted": "ગ્રુપ પૂરું કર્યું", "trustActiveDay": "દિવસની બધી એપ્સ ખોલી",
  "trustMissedDay": "એક દિવસ ચૂક્યા", "trustHelpfulFeedback": "ફીડબેક મદદરૂપ ગણાયો",
  "trustKickedInactive": "નિષ્ક્રિયતાને કારણે દૂર કરાયા", "trustKickedReported": "પુષ્ટ ફરિયાદ બાદ દૂર કરાયા",
  "trustSetupFailed": "સેટઅપ પૂરું ન થયું", "trustLeftGroup": "ગ્રુપ વહેલું છોડ્યું",
  "trustFalseReport": "એડમિને ફરિયાદ નકારી", "trustAppealAccepted": "અપીલ સ્વીકારાઈ",
  "statusSetup": "સેટઅપ", "statusActive": "ટેસ્ટિંગ", "statusCompleted": "પૂર્ણ", "statusCancelled": "રદ",
  "stateSetup": "સેટઅપ ચાલુ", "stateActive": "ટેસ્ટિંગ", "stateSuspended": "સમીક્ષા હેઠળ", "stateRemoved": "દૂર કરાયા", "stateCompleted": "પૂર્ણ",
  "language": "ભાષા", "tagline": "અસલી ટેસ્ટર. અસલી ફીડબેક.\nસાથે મળીને Google Play ક્લોઝ્ડ ટેસ્ટિંગ પાસ કરો.",
  "signInBullet1": "20 સુધી Android ડેવલપર્સના ગ્રુપમાં જોડાઓ",
  "signInBullet2": "ઇન્સ્ટોલ અને રોજનો ઉપયોગ ડિવાઇસ પર જ ચકાસાય છે",
  "signInBullet3": "પ્રામાણિક ફીડબેક આપો અને મેળવો, જેથી તમારી એપ વધુ સારી બને",
  "continueWithGoogle": "Google સાથે ચાલુ રાખો", "privacyPolicy": "પ્રાઇવસી પોલિસી", "terms": "શરતો",
  "ob1Title": "ડેવલપર્સ વચ્ચેનો કરાર",
  "ob1P1": "નવા પર્સનલ એકાઉન્ટને પ્રોડક્શન પહેલાં 14 દિવસ સુધી 12 ઓપ્ટ-ઇન ટેસ્ટર જોઈએ.",
  "ob1P2": "તમે એક ગ્રુપમાં જોડાઓ છો. બધા એકબીજાને ટેસ્ટર તરીકે ઉમેરે છે અને બધાની એપ્સ ઇન્સ્ટોલ કરે છે.",
  "ob1P3": "16 દિવસ સુધી તમે તમારી યાદીની દરેક એપ રોજ ખોલો છો, અને બાકીના બધા તમારી એપ માટે એ જ કરે છે.",
  "ob2Title": "બધા માટે ન્યાયી",
  "ob2P1": "તમે બીજાના ઈમેલ ઉમેરો પછી જ તમારી એપ તેમને દેખાય છે: પહેલા આપો, પછી મેળવો.",
  "ob2P2": "રોજ ટેસ્ટ કરવાથી અને મદદરૂપ ફીડબેક આપવાથી ટ્રસ્ટ સ્કોર વધે છે, ન કરવાથી ઘટે છે.",
  "ob2P3": "નિષ્ક્રિય સભ્યોને ચેતવણી મળે છે અને 3 દિવસ ચૂકે તો દૂર કરાય છે. ફરિયાદો અસલી વપરાશ ડેટા સામે ચકાસાય છે.",
  "ob3Title": "તમારું ટેસ્ટિંગ આપમેળે સાબિત કરો",
  "ob3P1": "TestPact ફક્ત તમને સોંપેલી એપ્સ તપાસે છે: ઇન્સ્ટોલ છે કે નહીં, અને આજે કેટલી મિનિટ વપરાઈ.",
  "ob3P2": "તમારી બીજી એપ્સ વિશે કંઈ પણ ક્યારેય વાંચવામાં કે મોકલવામાં આવતું નથી.",
  "usageAccessTitle": "યુસેજ એક્સેસ",
  "usageAccessBody": "આનાથી TestPact તમને સોંપેલી એપ્સમાં વિતાવેલી મિનિટો ગણી શકે છે, જેથી હોમ સ્ક્રીન પરથી ખોલો તો પણ તમને ક્રેડિટ મળે.",
  "granted": "મંજૂરી આપી ✓", "notGranted": "મંજૂરી નથી, ચાલુ કરવા ટેપ કરો", "grantUsageAccess": "યુસેજ એક્સેસ આપો",
  "notificationsTitle": "રિમાઇન્ડર", "notificationsBody": "રોજના રિમાઇન્ડર અને ગ્રુપ અપડેટ, જેથી એક પણ દિવસ ન ચૂકો.",
  "allowNotifications": "નોટિફિકેશનની મંજૂરી આપો", "getStarted": "શરૂ કરો", "settingUp": "તમારું એકાઉન્ટ તૈયાર થઈ રહ્યું છે…",
  "signOut": "સાઇન આઉટ", "tabHome": "હોમ", "tabMyApps": "મારી એપ્સ", "tabFeedback": "ફીડબેક", "tabProfile": "પ્રોફાઇલ",
  "admin": "એડમિન", "settings": "સેટિંગ્સ", "addApp": "એપ ઉમેરો",
  "bannedTitle": "એકાઉન્ટ પ્રતિબંધિત",
  "bannedBody": "તમારા {count} સ્ટ્રાઇક છે, એટલે તમે નવા ગ્રુપમાં જોડાઈ શકતા નથી. જો આ ભૂલ લાગે તો અપીલ મોકલો.",
  "appeal": "અપીલ",
  "strikesTitle": "તમારા એકાઉન્ટ પર {count} સ્ટ્રાઇક",
  "strikesBody": "3 સ્ટ્રાઇક થાય તો તમે નવા ગ્રુપમાં જોડાઈ શકતા નથી. નિષ્ક્રિયતા અથવા પુષ્ટ ફરિયાદથી દૂર થવા પર સ્ટ્રાઇક મળે છે.",
  "howItWorks": "આ કેવી રીતે કામ કરે છે",
  "googleRuleTitle": "Google Play નો નિયમ",
  "googleRuleBody": "13 નવેમ્બર 2023 પછી બનેલા પર્સનલ ડેવલપર એકાઉન્ટને સતત 14 દિવસ સુધી ઓછામાં ઓછા 12 ઓપ્ટ-ઇન ટેસ્ટર જોઈએ. ગ્રુપ 20 લોકોથી શરૂ થાય છે અને 16 દિવસ ચાલે છે, જેથી તમારી પાસે ગાળો રહે. Google એ પણ જુએ છે કે ટેસ્ટર્સે એપ ખરેખર વાપરી કે નહીં, એટલે ફક્ત ઇન્સ્ટોલ ન કરો, એપ ખોલીને વાપરો.",
  "hello": "નમસ્તે, {name} 👋",
  "joinCardTitle": "તમારા ટેસ્ટર શોધવા તૈયાર છો?",
  "joinCardBody": "કતારમાં જોડાઓ. પૂરતા ડેવલપર થતાં જ તમારું ગ્રુપ આપમેળે બની જશે.",
  "joinCardNoApps": "પહેલા જે એપ ટેસ્ટ કરાવવી છે તે ઉમેરો, તેની ક્લોઝ્ડ ટેસ્ટિંગ લિંક સાથે.",
  "joinGroup": "ગ્રુપમાં જોડાઓ", "addYourApp": "તમારી એપ ઉમેરો",
  "inQueueTitle": "તમે કતારમાં છો",
  "inQueueBody": "{app} ને {tier} ગ્રુપમાં જોડવાની રાહ જોવાય છે. તૈયાર થતાં અમે તમને જાણ કરીશું.",
  "tierTrusted": "વિશ્વસનીય", "tierStarter": "સ્ટાર્ટર",
  "queueWaiting": "{size} માંથી {count} ડેવલપર રાહ જુએ છે", "queueJoinedAt": "{time} એ જોડાયા", "leaveQueue": "કતાર છોડો",
  "dayOf": "દિવસ {day} / {total}", "groupTitle": "ગ્રુપ #{id}",
  "openedToday": "આજે ખોલી: {total} માંથી {opened}",
  "setupDoneWaiting": "સેટઅપ પૂર્ણ ✓ બાકીના સભ્યોની રાહ છે.",
  "setupTodo": "સેટઅપ પૂરું કરો: ઈમેલ ઉમેરો અને બધાની એપ્સ ઇન્સ્ટોલ કરો.",
  "suspendedBody": "ઘણી ફરિયાદો બાદ તમે સમીક્ષા હેઠળ છો. એડમિન તમારો એક્ટિવિટી ડેટા તપાસી રહ્યા છે.",
  "openGroup": "ગ્રુપ ખોલો",
  "step1Title": "તમારી એપ ઉમેરો", "step1Body": "નામ, પેકેજ અને તમારી ક્લોઝ્ડ ટેસ્ટિંગ ઓપ્ટ-ઇન લિંક.",
  "step2Title": "કતારમાં જોડાઓ", "step2Body": "20 લોકોના ગ્રુપ આપમેળે બને છે. વિશ્વસનીય ટેસ્ટર્સ સાથે જોડાય છે.",
  "step3Title": "48 કલાકમાં સેટઅપ", "step3Body": "બધાના ઈમેલ Play Console માં પેસ્ટ કરો, પછી દરેક એપમાં જોડાઓ અને ઇન્સ્ટોલ કરો.",
  "step4Title": "16 દિવસ રોજ ટેસ્ટ કરો", "step4Body": "દરેક એપ રોજ ખોલો અને અસલી ફીડબેક આપો. અમે ડિવાઇસ પર ચકાસીએ છીએ.",
  "step5Title": "પ્રોડક્શન માટે અરજી", "step5Body": "ટ્રસ્ટ પોઇન્ટ અને બેજ મેળવો, પછી Play Console માં પ્રોડક્શન માટે અરજી કરો.",
  "rule1": "હું 48 કલાકમાં દરેક સભ્યનો ઈમેલ મારા ક્લોઝ્ડ ટેસ્ટમાં ઉમેરીશ.",
  "rule2": "હું દરેક સભ્યની એપ ઇન્સ્ટોલ કરીશ અને અંત સુધી ઇન્સ્ટોલ રાખીશ.",
  "rule3": "હું 16 દિવસ સુધી રોજ દરેક એપ ખોલીશ અને પ્રામાણિક ફીડબેક આપીશ.",
  "rule4": "હું સમજું છું કે નિષ્ક્રિય સભ્યો દૂર કરાય છે અને ટ્રસ્ટ પોઇન્ટ ગુમાવે છે.",
  "chooseApp": "કઈ એપ ટેસ્ટ થવી જોઈએ?", "yourCommitment": "તમારું વચન",
  "joinedQueue": "તમે કતારમાં છો!", "joinQueue": "કતારમાં જોડાઓ",
  "noAppsTitle": "હજુ કોઈ એપ નથી", "noAppsBody": "જે એપ ટેસ્ટ કરાવવી છે તે ઉમેરો. આ માટે Play Console માંથી ક્લોઝ્ડ ટેસ્ટિંગ ઓપ્ટ-ઇન લિંક જોઈશે.",
  "deleteAppTitle": "આ એપ કાઢી નાખવી?", "deleteAppBody": "જે ગ્રુપમાં તે પહેલેથી છે ત્યાં તેની કોપી રહેશે. તમે પછી ફરી ઉમેરી શકો છો.",
  "editApp": "એપ બદલો", "appIcon": "આઇકન સેટ કરવા ટેપ કરો", "appName": "એપનું નામ", "packageName": "પેકેજ નામ",
  "invalidPackage": "સાચું પેકેજ નામ લખો, જેમ કે com.example.app",
  "optInLink": "ક્લોઝ્ડ ટેસ્ટિંગ ઓપ્ટ-ઇન લિંક",
  "optInHelp": "Play Console → Testing → Closed testing → Testers → \"Join on the web\" લિંક.",
  "invalidOptIn": "આ play.google.com/apps/testing/… લિંક હોવી જોઈએ",
  "shortDescription": "ટૂંકું વર્ણન", "testNotes": "ટેસ્ટર્સ શું અજમાવે?",
  "testNotesHelp": "જેમ કે \"એકાઉન્ટ બનાવો અને કાર્ટમાં 2 વસ્તુ ઉમેરો\". આ ટેસ્ટર્સને રોજ દેખાશે.",
  "closedTestTipTitle": "જોડાતા પહેલાં",
  "closedTestTipBody": "ક્લોઝ્ડ ટેસ્ટિંગ ટ્રેક બનાવો, બિલ્ડ અપલોડ કરીને રોલ આઉટ કરો અને ટેસ્ટર્સને ઈમેલ લિસ્ટ પર સેટ કરો. તમારા ગ્રુપના ઈમેલ ત્યાં જશે.",
  "tabToday": "આજે", "tabSetup": "સેટઅપ", "tabMembers": "સભ્યો", "tabActivity": "પ્રવૃત્તિ",
  "leaveGroup": "ગ્રુપ છોડો", "leaveGroupTitle": "આ ગ્રુપ છોડવું?",
  "leaveGroupBody": "બાકીના સભ્યો તમારી એપ ટેસ્ટ કરવાનું બંધ કરશે અને તમારા ટ્રસ્ટ પોઇન્ટ ઘટશે. આ પાછું ફેરવી શકાશે નહીં.",
  "youWereRemoved": "તમને દૂર કરાયા: {reason}.",
  "youCompleted": "તમે આ ગ્રુપ પૂરું કર્યું 🏆 હવે તમે Play Console માં પ્રોડક્શન એક્સેસ માટે અરજી કરી શકો છો.",
  "setupDeadlinePassed": "સેટઅપની સમયમર્યાદા પૂરી. પ્રક્રિયા ચાલુ છે…",
  "setupTimeLeft": "સેટઅપ પૂરું કરવા {hours}ક {minutes}મિ બાકી",
  "setupExplain": "જે સભ્યો પૂરું નથી કરતા, તેમની જગ્યાએ કતારમાંથી લોકો આવે છે. બધા તૈયાર થાય ત્યારે ટેસ્ટ શરૂ થાય છે.",
  "step1AddEmails": "પગલું 1 · તમારા ક્લોઝ્ડ ટેસ્ટમાં ટેસ્ટર ઉમેરો",
  "addEmailsBody": "બધા {count} ઈમેલ કોપી કરો અને Play Console માં તમારી ક્લોઝ્ડ ટેસ્ટિંગ ઈમેલ લિસ્ટમાં પેસ્ટ કરો.",
  "copyAllEmails": "બધા ઈમેલ કોપી કરો", "copied": "{count} ઈમેલ કોપી થયા",
  "emailsConfirmed": "ઈમેલ ઉમેરાયા", "iAddedEveryone": "મેં બધાને ઉમેર્યા",
  "confirmEmailsTitle": "શું તમે બધા ઈમેલ ઉમેર્યા?",
  "confirmEmailsBody": "પુષ્ટિ કરો કે બધા {count} ઈમેલ તમારા ક્લોઝ્ડ ટેસ્ટની ટેસ્ટર લિસ્ટમાં છે અને ફેરફાર સેવ થયો છે. જો સભ્યો જોડાઈ ન શકે તો તેઓ તમારી ફરિયાદ કરી શકે છે.",
  "yesAdded": "હા, બધા ઉમેર્યા",
  "emailsHowTo": "Play Console → તમારી એપ → Testing → Closed testing → Testers → Email list → પેસ્ટ → Save.",
  "step2InstallApps": "પગલું 2 · એપ્સમાં જોડાઓ અને ઇન્સ્ટોલ કરો ({done}/{total})",
  "checkAgain": "ફરી તપાસો",
  "waitingForOwners": "{count} સભ્યોએ હજુ ગ્રુપના ઈમેલ ઉમેર્યા નથી. ઉમેર્યા પછી તેમની એપ્સ અહીં દેખાશે.",
  "noAppsYet": "હજુ ઇન્સ્ટોલ કરવા કોઈ એપ નથી.", "byName": "{name} દ્વારા", "joinTest": "ટેસ્ટમાં જોડાઓ",
  "newMembersTitle": "નવા સભ્ય જોડાયા",
  "newMembersBody": "નવા ઈમેલ તમારા ક્લોઝ્ડ ટેસ્ટમાં ઉમેરો અને તેમની એપ ઇન્સ્ટોલ કરો. સેટઅપ ટેબ ખોલો.",
  "usageAccessOffTitle": "યુસેજ એક્સેસ બંધ છે",
  "usageAccessOffBody": "ફક્ત ખોલો બટનથી ખોલેલી એપ્સ ગણાય છે. હોમ સ્ક્રીન પરથી ખોલો ત્યારે પણ ક્રેડિટ મેળવવા યુસેજ એક્સેસ ચાલુ કરો.",
  "yourTestList": "તમારી ટેસ્ટ યાદી",
  "todayTitle": "આજનું ટેસ્ટિંગ", "todayDone": "આજનું બધું પૂરું 🎉", "todayDoneBody": "શાબાશ! કાલે ફરી આવજો.",
  "todayBody": "ઓછામાં ઓછી {needed} એપ્સ ખોલો અને દરેકને થોડી વાર વાપરો.",
  "dayResetsAt": "નવો દિવસ {time} વાગ્યે શરૂ થાય છે",
  "notInstalled": "ઇન્સ્ટોલ નથી", "openedMinutes": "આજે ખોલી · {minutes} મિનિટ", "notOpenedYet": "આજે ખોલી નથી",
  "feedbackGivenCount": "ફીડબેક ({count})", "giveFeedback": "ફીડબેક",
  "statMembers": "સભ્યો", "statOnTrack": "આજે સાચા માર્ગે", "statRemoved": "દૂર કરાયા",
  "membersLegend": "🟢 સાચા માર્ગે  🟡 હજુ બાકી  🔴 દિવસ ચૂક્યા  ⚪ ગયા",
  "memberSetupLine": "ઈમેલ {emails} · ઇન્સ્ટોલ {installed}/{total}",
  "memberActiveLine": "ઇન્સ્ટોલ {installed}/{total} · ખોલી {opened}/{total} · ફીડબેક {feedback}",
  "missedInARow": "સતત {count} દિવસ ચૂક્યા",
  "lastDays": "છેલ્લા દિવસો", "viewProfile": "પ્રોફાઇલ જુઓ", "openInPlay": "Play Store માં ખોલો", "reportMember": "ફરિયાદ કરો",
  "reportSent": "ફરિયાદ મોકલાઈ. ગ્રુપને ન્યાયી રાખવા બદલ આભાર.",
  "reportTitle": "{name} ની ફરિયાદ કરો",
  "reportExplain": "પગલાં ત્યારે જ લેવાય છે જ્યારે ઘણા સભ્યો ફરિયાદ કરે અને અમારો વપરાશ ડેટા પણ સહમત હોય. ખોટી ફરિયાદ પર ટ્રસ્ટ પોઇન્ટ ઘટે છે.",
  "detailsOptional": "વિગતો (વૈકલ્પિક)", "addScreenshot": "સ્ક્રીનશોટ ઉમેરો", "screenshotAdded": "સ્ક્રીનશોટ ઉમેરાયો ✓",
  "sendReport": "ફરિયાદ મોકલો", "noActivity": "હજુ કોઈ પ્રવૃત્તિ નથી",
  "evFormed": "{count} ડેવલપર્સ સાથે ગ્રુપ બન્યું", "evJoined": "{name} ગ્રુપમાં જોડાયા",
  "evEmailsAdded": "{name} એ બધાના ઈમેલ ઉમેર્યા", "evStarted": "ટેસ્ટિંગ શરૂ: દિવસ 1",
  "evMemberActive": "{name} એ સેટઅપ પૂરું કરી ટેસ્ટિંગ શરૂ કર્યું", "evWarning": "{name} સતત 2 દિવસ ચૂક્યા (છેલ્લી ચેતવણી)",
  "evRemoved": "{name} ને દૂર કરાયા ({reason})", "evSuspended": "{name} એડમિન સમીક્ષા હેઠળ છે",
  "evReinstated": "{name} નિર્દોષ ઠર્યા અને પાછા આવ્યા", "evCompleted": "ગ્રુપ પૂરું થયું 🏆", "evCancelled": "ગ્રુપ રદ થયું",
  "feedbackSent": "ફીડબેક મોકલાયો. આભાર!", "feedbackFor": "ફીડબેક: {app}",
  "developerAsks": "ડેવલપર તમને આ અજમાવવા કહે છે", "rating": "રેટિંગ", "category": "શ્રેણી",
  "yourFeedback": "તમારો ફીડબેક",
  "feedbackHint": "શું સારું ચાલ્યું, શું તૂટ્યું, શું ગૂંચવણભર્યું લાગ્યું? સ્પષ્ટ લખો: સ્ક્રીન, પગલાં, ડિવાઇસ.",
  "feedbackMin": "ઓછામાં ઓછા 20 અક્ષર", "sendFeedback": "ફીડબેક મોકલો",
  "received": "મળેલા", "given": "આપેલા",
  "noFeedbackReceived": "હજુ કોઈ ફીડબેક નથી", "noFeedbackReceivedBody": "તમારા ગ્રુપના ટેસ્ટર્સનો ફીડબેક અહીં દેખાશે.",
  "noFeedbackGiven": "તમે હજુ ફીડબેક આપ્યો નથી", "noFeedbackGivenBody": "ગ્રુપના આજે ટેબમાં દરેક એપ પરનું ફીડબેક બટન વાપરો.",
  "fromOnApp": "{name}, {app} પર", "wasHelpful": "શું આ મદદરૂપ હતું?",
  "markedHelpful": "તમે આને મદદરૂપ ગણાવ્યું (તેમને +2 ટ્રસ્ટ)", "markedNotHelpful": "મદદરૂપ નથી ગણાવ્યું",
  "groupHistory": "ગ્રુપ", "noGroupsYet": "હજુ કોઈ ગ્રુપ નથી.",
  "trustHistory": "ટ્રસ્ટ સ્કોર ઇતિહાસ", "noTrustHistory": "હજુ કોઈ ફેરફાર નથી.",
  "trustScore": "ટ્રસ્ટ સ્કોર", "pointsToNext": "આગળના લેવલ માટે {points} પોઇન્ટ",
  "statCompleted": "પૂરા કરેલા ગ્રુપ", "statCompletionRate": "પૂર્ણતા દર", "statDailyActivity": "રોજની પ્રવૃત્તિ",
  "statActiveDays": "સક્રિય દિવસો", "statFeedback": "આપેલા ફીડબેક", "statHelpful": "મદદરૂપ ફીડબેક",
  "badges": "બેજ", "noBadges": "બેજ મેળવવા તમારું પહેલું ગ્રુપ પૂરું કરો.",
  "systemLanguage": "સિસ્ટમ ડિફોલ્ટ", "general": "સામાન્ય", "about": "માહિતી",
  "contactSupport": "સપોર્ટનો સંપર્ક", "rateApp": "TestPact ને રેટ કરો", "account": "એકાઉન્ટ",
  "deleteAccount": "એકાઉન્ટ કાઢી નાખો", "deleteAccountTitle": "તમારું એકાઉન્ટ કાઢી નાખવું?",
  "deleteAccountBody": "તમારી પ્રોફાઇલ, એપ્સ અને ટ્રસ્ટ સ્કોર કાયમ માટે કાઢી નખાશે. જો તમે કોઈ ગ્રુપમાં હો તો તેમાંથી દૂર થશો.",
  "appealTitle": "કોઈ નિર્ણય સામે અપીલ કરો",
  "appealExplain": "શું થયું તે જણાવો. એડમિન દરેક અપીલની સમીક્ષા કરે છે. સ્વીકારાય તો એક સ્ટ્રાઇક દૂર થાય છે અને થોડા ટ્રસ્ટ પોઇન્ટ પાછા મળે છે.",
  "appealHint": "શું થયું? તારીખો અને તપાસમાં મદદ કરે તેવી કોઈ પણ માહિતી લખો.",
  "appealSent": "અપીલ મોકલાઈ", "sendAppeal": "અપીલ મોકલો", "yourAppeals": "તમારી અપીલો",
  "appealOpen": "સમીક્ષાની રાહ", "appealAccepted": "સ્વીકારાઈ", "appealRejected": "નકારાઈ",
  "adminReviews": "સમીક્ષાઓ", "adminAppeals": "અપીલો", "adminUsers": "યુઝર્સ",
  "noteOptional": "યુઝર માટે નોંધ (વૈકલ્પિક)", "nothingToReview": "સમીક્ષા માટે કંઈ નથી 🎉",
  "dataSummary": "વપરાશ ડેટા: {active} સક્રિય દિવસ, {missed} ચૂકેલા દિવસ",
  "rejectReports": "ફરિયાદો નકારો", "confirmKick": "પુષ્ટિ કરી દૂર કરો",
  "searchByEmail": "ઈમેલથી યુઝર શોધો", "userNotFound": "આ ઈમેલનો કોઈ યુઝર નથી.",
  "userSummary": "ટ્રસ્ટ {trust} · સ્ટ્રાઇક {strikes} · બૅન: {banned}",
  "ban": "બૅન કરો", "unban": "બૅન હટાવો", "adjustTrust": "ટ્રસ્ટ સ્કોર બદલો",

  "notificationsInbox": "નોટિફિકેશન", "markAllRead": "બધા વાંચેલા કરો",
  "noNotifications": "હજુ કોઈ નોટિફિકેશન નથી",
  "noNotificationsBody": "ગ્રુપ અપડેટ, રિમાઇન્ડર, ચેતવણીઓ અને ફીડબેક એલર્ટ અહીં દેખાશે.",
  "notificationSettings": "નોટિફિકેશન",
  "notifPermissionOff": "TestPact માટે નોટિફિકેશન બંધ છે", "openSettings": "સેટિંગ્સ ખોલો",
  "notifDaily": "રોજના રિમાઇન્ડર",
  "notifDailySub": "જો આજની એપ્સ ન ખોલી હોય તો સાંજે રિમાઇન્ડર, અને સેટઅપની સમયમર્યાદા",
  "notifGroup": "ગ્રુપ અપડેટ", "notifGroupSub": "ગ્રુપ બન્યું, ટેસ્ટ શરૂ, નવા સભ્યો, પૂર્ણતા",
  "notifFeedback": "ફીડબેક", "notifFeedbackSub": "જ્યારે કોઈ તમારી એપ પર ફીડબેક આપે",
  "notifImportantNote": "ચેતવણીઓ અને દૂર કરવાની સૂચના હંમેશા મોકલાય છે, જેથી તમારી જગ્યાને લગતી કોઈ વાત ચૂકો નહીં.",
  "noInternetTitle": "ઇન્ટરનેટ કનેક્શન નથી",
  "noInternetBody": "તમારું Wi-Fi અથવા મોબાઇલ ડેટા તપાસો. ઓનલાઇન થતાં જ TestPact આપમેળે જોડાઈ જશે.",
  "checkingConnection": "તપાસી રહ્યા છીએ…", "backOnline": "ફરી ઓનલાઇન",
  "updateRequiredTitle": "અપડેટ જરૂરી છે",
  "updateRequiredBody": "TestPact નું આ વર્ઝન હવે સપોર્ટેડ નથી. તમારા ગ્રુપ સાથે ટેસ્ટિંગ ચાલુ રાખવા અપડેટ કરો.",
  "updateAvailableTitle": "અપડેટ ઉપલબ્ધ છે",
  "updateAvailableBody": "TestPact નું નવું વર્ઝન સુધારા અને ફિક્સ સાથે તૈયાર છે.",
  "updateNow": "હમણાં અપડેટ કરો", "later": "પછી",
  "updateDownloaded": "અપડેટ ડાઉનલોડ થયું. ઇન્સ્ટોલ પૂરું કરવા રીસ્ટાર્ટ કરો.", "restart": "રીસ્ટાર્ટ",
  "appVersion": "વર્ઝન {version}",

  "welcomeBack": "તમને ફરી જોઈને આનંદ થયો!", "viewAll": "બધું જુઓ", "more": "વધુ",
  "filterAll": "બધી", "statusTesting": "ટેસ્ટિંગ", "inQueueShort": "કતારમાં", "statusReady": "તૈયાર",
  "memberDone": "પૂર્ણ", "memberTesting": "ટેસ્ટિંગ", "memberPending": "આજે બાકી",
  "todaysTasks": "આજના કામ",
  "tasksCompleted": "{total} એપ્સ · {done}/{total} પૂર્ણ",
  "groupMembersCount": "ગ્રુપ સભ્યો ({count})",
  "recentActivity": "તાજેતરની પ્રવૃત્તિ",
  "badgesEarned": "{total} માંથી {earned} મળ્યા",
}
