T = {
  "cancel": "रद्द करें", "save": "सेव करें", "saved": "सेव हो गया", "delete": "हटाएं", "edit": "बदलें",
  "next": "आगे", "retry": "फिर कोशिश करें", "yes": "हाँ", "no": "नहीं", "you": "आप",
  "required": "ज़रूरी है", "open": "खोलें", "install": "इंस्टॉल करें", "leave": "छोड़ें",
  "accept": "स्वीकार करें", "reject": "अस्वीकार करें", "confirmAction": "पुष्टि करें",
  "errDeviceInUse": "यह फ़ोन पहले से किसी दूसरे TestPact अकाउंट से जुड़ा है। हर डिवाइस पर एक अकाउंट से ग्रुप निष्पक्ष रहते हैं।",
  "errBanned": "अभी आपका अकाउंट नए ग्रुप में शामिल नहीं हो सकता। आप अपील भेज सकते हैं।",
  "errAlreadyInGroup": "आप पहले से एक ग्रुप में हैं। पहले उसे पूरा करें।",
  "errAppNotFound": "यह ऐप लिस्टिंग अब मौजूद नहीं है।",
  "errAppealOpen": "आपकी एक अपील पहले से समीक्षा के लिए लंबित है।",
  "errAlreadyRated": "आप इस फीडबैक को पहले ही रेट कर चुके हैं।",
  "errIntegrity": "यह डिवाइस Google Play की इंटीग्रिटी जांच में पास नहीं हुआ। Google Play से इंस्टॉल किए ऐप के साथ असली फ़ोन इस्तेमाल करें।",
  "errNetwork": "कनेक्शन नहीं है। इंटरनेट जांचें और फिर कोशिश करें।",
  "errGeneric": "कुछ गड़बड़ हो गई। कृपया फिर कोशिश करें।",
  "levelProbation": "प्रोबेशन", "levelNewcomer": "नया सदस्य", "levelMember": "सदस्य", "levelTrusted": "भरोसेमंद", "levelTopTester": "टॉप टेस्टर",
  "reasonNotInstalled": "मेरा ऐप इंस्टॉल नहीं किया", "reasonUninstalled": "टेस्ट के दौरान अनइंस्टॉल किया",
  "reasonNotOpening": "रोज़ ऐप नहीं खोल रहे", "reasonEmailNotAdded": "मेरा ईमेल अपने टेस्ट में नहीं जोड़ा",
  "reasonSpam": "स्पैम या दुर्व्यवहार", "reasonFakeFeedback": "नकली या कॉपी-पेस्ट फीडबैक", "reasonOther": "अन्य",
  "catBug": "बग", "catUx": "डिज़ाइन / UX", "catIdea": "सुझाव", "catPraise": "तारीफ़", "catOther": "अन्य",
  "badgeFirstPact": "पहला पैक्ट", "badgeVeteran": "अनुभवी (5 ग्रुप)", "badgePerfect": "परफेक्ट स्ट्रीक",
  "badgeHelpful": "मददगार समीक्षक", "badgeTopTester": "टॉप टेस्टर",
  "removedSetup": "सेटअप समय पर पूरा नहीं हुआ", "removedInactive": "3 दिन से निष्क्रिय",
  "removedReported": "एडमिन ने रिपोर्ट की पुष्टि की", "removedLeft": "ग्रुप छोड़ दिया",
  "removedCancelled": "ग्रुप रद्द हुआ", "removedEnded": "ग्रुप समाप्त हुआ", "removedOther": "हटाया गया",
  "trustAdmin": "एडमिन द्वारा बदलाव: {reason}",
  "trustGroupCompleted": "ग्रुप पूरा किया", "trustActiveDay": "दिन के सभी ऐप खोले",
  "trustMissedDay": "एक दिन छूटा", "trustHelpfulFeedback": "फीडबैक मददगार माना गया",
  "trustKickedInactive": "निष्क्रियता के कारण हटाया गया", "trustKickedReported": "पुष्ट रिपोर्ट के बाद हटाया गया",
  "trustSetupFailed": "सेटअप पूरा नहीं हुआ", "trustLeftGroup": "ग्रुप जल्दी छोड़ा",
  "trustFalseReport": "एडमिन ने रिपोर्ट खारिज की", "trustAppealAccepted": "अपील स्वीकार हुई",
  "statusSetup": "सेटअप", "statusActive": "टेस्टिंग", "statusCompleted": "पूरा", "statusCancelled": "रद्द",
  "stateSetup": "सेटअप जारी", "stateActive": "टेस्टिंग", "stateSuspended": "समीक्षा में", "stateRemoved": "हटाया गया", "stateCompleted": "पूरा",
  "language": "भाषा", "tagline": "असली टेस्टर। असली फीडबैक।\nसाथ मिलकर Google Play क्लोज़्ड टेस्टिंग पास करें।",
  "signInBullet1": "20 तक Android डेवलपर्स के ग्रुप में जुड़ें",
  "signInBullet2": "इंस्टॉल और रोज़ का इस्तेमाल डिवाइस पर ही वेरिफ़ाई होता है",
  "signInBullet3": "ईमानदार फीडबैक दें और पाएं, जिससे आपका ऐप बेहतर बने",
  "continueWithGoogle": "Google से जारी रखें", "privacyPolicy": "प्राइवेसी पॉलिसी", "terms": "शर्तें",
  "ob1Title": "डेवलपर्स के बीच एक समझौता",
  "ob1P1": "नए पर्सनल अकाउंट को प्रोडक्शन से पहले 14 दिनों तक 12 ऑप्ट-इन टेस्टर चाहिए।",
  "ob1P2": "आप एक ग्रुप में जुड़ते हैं। सब एक-दूसरे को टेस्टर के रूप में जोड़ते हैं और सबके ऐप इंस्टॉल करते हैं।",
  "ob1P3": "16 दिनों तक आप अपनी सूची का हर ऐप रोज़ खोलते हैं, और बाकी सब आपके ऐप के लिए यही करते हैं।",
  "ob2Title": "सबके लिए निष्पक्ष",
  "ob2P1": "आपका ऐप दूसरों को तभी दिखता है जब आप उनके ईमेल जोड़ देते हैं: पहले दें, फिर पाएं।",
  "ob2P2": "रोज़ टेस्ट करने और मददगार फीडबैक देने पर ट्रस्ट स्कोर बढ़ता है, न करने पर घटता है।",
  "ob2P3": "निष्क्रिय सदस्यों को चेतावनी मिलती है और 3 दिन चूकने पर हटा दिए जाते हैं। रिपोर्ट को असली इस्तेमाल डेटा से जांचा जाता है।",
  "ob3Title": "अपनी टेस्टिंग अपने-आप साबित करें",
  "ob3P1": "TestPact केवल आपको दिए गए ऐप्स जांचता है: इंस्टॉल हैं या नहीं, और आज कितने मिनट इस्तेमाल हुए।",
  "ob3P2": "आपके बाकी ऐप्स के बारे में कुछ भी कभी पढ़ा या भेजा नहीं जाता।",
  "usageAccessTitle": "यूसेज एक्सेस",
  "usageAccessBody": "इससे TestPact आपके दिए गए ऐप्स में बिताए मिनट गिन पाता है, ताकि होम स्क्रीन से खोलने पर भी आपको क्रेडिट मिले।",
  "granted": "अनुमति दी गई ✓", "notGranted": "अनुमति नहीं, चालू करने के लिए टैप करें", "grantUsageAccess": "यूसेज एक्सेस दें",
  "notificationsTitle": "रिमाइंडर", "notificationsBody": "रोज़ के रिमाइंडर और ग्रुप अपडेट, ताकि कोई दिन न छूटे।",
  "allowNotifications": "नोटिफिकेशन की अनुमति दें", "getStarted": "शुरू करें", "settingUp": "आपका अकाउंट तैयार हो रहा है…",
  "signOut": "साइन आउट", "tabHome": "होम", "tabMyApps": "मेरे ऐप", "tabFeedback": "फीडबैक", "tabProfile": "प्रोफ़ाइल",
  "admin": "एडमिन", "settings": "सेटिंग्स", "addApp": "ऐप जोड़ें",
  "bannedTitle": "अकाउंट प्रतिबंधित",
  "bannedBody": "आपके {count} स्ट्राइक हैं, इसलिए आप नए ग्रुप में नहीं जुड़ सकते। अगर यह गलती लगती है तो अपील भेजें।",
  "appeal": "अपील",
  "strikesTitle": "आपके अकाउंट पर {count} स्ट्राइक",
  "strikesBody": "3 स्ट्राइक होने पर आप नए ग्रुप में नहीं जुड़ सकते। स्ट्राइक निष्क्रियता या पुष्ट रिपोर्ट से हटाए जाने पर मिलते हैं।",
  "howItWorks": "यह कैसे काम करता है",
  "googleRuleTitle": "Google Play का नियम",
  "googleRuleBody": "13 नवंबर 2023 के बाद बने पर्सनल डेवलपर अकाउंट को लगातार 14 दिनों तक कम से कम 12 ऑप्ट-इन टेस्टर चाहिए। ग्रुप 20 लोगों से शुरू होते हैं और 16 दिन चलते हैं, ताकि आपके पास गुंजाइश रहे। Google यह भी देखता है कि टेस्टर्स ने ऐप सच में इस्तेमाल किया या नहीं, इसलिए सिर्फ़ इंस्टॉल न करें, ऐप खोलकर इस्तेमाल करें।",
  "hello": "नमस्ते, {name} 👋",
  "joinCardTitle": "अपने टेस्टर ढूंढने के लिए तैयार?",
  "joinCardBody": "कतार में जुड़ें। जैसे ही पर्याप्त डेवलपर होंगे, आपका ग्रुप अपने-आप बन जाएगा।",
  "joinCardNoApps": "पहले वह ऐप जोड़ें जिसे टेस्ट कराना है, उसके क्लोज़्ड टेस्टिंग लिंक के साथ।",
  "joinGroup": "ग्रुप में जुड़ें", "addYourApp": "अपना ऐप जोड़ें",
  "inQueueTitle": "आप कतार में हैं",
  "inQueueBody": "{app} को {tier} ग्रुप में मिलाने का इंतज़ार है। तैयार होने पर हम आपको सूचित करेंगे।",
  "tierTrusted": "भरोसेमंद", "tierStarter": "स्टार्टर",
  "queueWaiting": "{size} में से {count} डेवलपर इंतज़ार में", "queueJoinedAt": "{time} को जुड़े", "leaveQueue": "कतार छोड़ें",
  "dayOf": "दिन {day} / {total}", "groupTitle": "ग्रुप #{id}",
  "openedToday": "आज खोले: {total} में से {opened}",
  "setupDoneWaiting": "सेटअप पूरा ✓ बाकी सदस्यों का इंतज़ार है।",
  "setupTodo": "सेटअप पूरा करें: ईमेल जोड़ें और सबके ऐप इंस्टॉल करें।",
  "suspendedBody": "कई रिपोर्ट के बाद आप समीक्षा में हैं। एडमिन आपका एक्टिविटी डेटा जांच रहे हैं।",
  "openGroup": "ग्रुप खोलें",
  "step1Title": "अपना ऐप जोड़ें", "step1Body": "नाम, पैकेज और आपका क्लोज़्ड टेस्टिंग ऑप्ट-इन लिंक।",
  "step2Title": "कतार में जुड़ें", "step2Body": "20 लोगों के ग्रुप अपने-आप बनते हैं। भरोसेमंद टेस्टर्स साथ मिलाए जाते हैं।",
  "step3Title": "48 घंटे में सेटअप", "step3Body": "सबके ईमेल Play Console में पेस्ट करें, फिर हर ऐप में जुड़ें और इंस्टॉल करें।",
  "step4Title": "16 दिन रोज़ टेस्ट करें", "step4Body": "हर ऐप रोज़ खोलें और असली फीडबैक दें। हम डिवाइस पर इसे वेरिफ़ाई करते हैं।",
  "step5Title": "प्रोडक्शन के लिए आवेदन", "step5Body": "ट्रस्ट पॉइंट और बैज कमाएं, फिर Play Console में प्रोडक्शन के लिए आवेदन करें।",
  "rule1": "मैं 48 घंटे में हर सदस्य का ईमेल अपने क्लोज़्ड टेस्ट में जोड़ूंगा/जोड़ूंगी।",
  "rule2": "मैं हर सदस्य का ऐप इंस्टॉल करूंगा/करूंगी और अंत तक इंस्टॉल रखूंगा/रखूंगी।",
  "rule3": "मैं 16 दिनों तक रोज़ हर ऐप खोलूंगा/खोलूंगी और ईमानदार फीडबैक दूंगा/दूंगी।",
  "rule4": "मैं समझता/समझती हूँ कि निष्क्रिय सदस्य हटाए जाते हैं और ट्रस्ट पॉइंट खोते हैं।",
  "chooseApp": "कौन सा ऐप टेस्ट होना चाहिए?", "yourCommitment": "आपका वादा",
  "joinedQueue": "आप कतार में हैं!", "joinQueue": "कतार में जुड़ें",
  "noAppsTitle": "अभी कोई ऐप नहीं", "noAppsBody": "जिस ऐप को टेस्ट कराना है उसे जोड़ें। इसके लिए Play Console से क्लोज़्ड टेस्टिंग ऑप्ट-इन लिंक चाहिए।",
  "deleteAppTitle": "यह ऐप हटाएं?", "deleteAppBody": "जिन ग्रुप्स में यह पहले से है, उनमें इसकी कॉपी रहेगी। आप इसे बाद में फिर जोड़ सकते हैं।",
  "editApp": "ऐप बदलें", "appIcon": "आइकन सेट करने के लिए टैप करें", "appName": "ऐप का नाम", "packageName": "पैकेज नाम",
  "invalidPackage": "सही पैकेज नाम लिखें, जैसे com.example.app",
  "optInLink": "क्लोज़्ड टेस्टिंग ऑप्ट-इन लिंक",
  "optInHelp": "Play Console → Testing → Closed testing → Testers → \"Join on the web\" लिंक।",
  "invalidOptIn": "यह play.google.com/apps/testing/… लिंक होना चाहिए",
  "shortDescription": "छोटा विवरण", "testNotes": "टेस्टर्स क्या आज़माएं?",
  "testNotesHelp": "जैसे \"अकाउंट बनाएं और कार्ट में 2 आइटम जोड़ें\"। यह टेस्टर्स को रोज़ दिखेगा।",
  "closedTestTipTitle": "जुड़ने से पहले",
  "closedTestTipBody": "क्लोज़्ड टेस्टिंग ट्रैक बनाएं, बिल्ड अपलोड करके रोल आउट करें, और टेस्टर्स को ईमेल लिस्ट पर सेट करें। आपके ग्रुप के ईमेल वहीं जाएंगे।",
  "tabToday": "आज", "tabSetup": "सेटअप", "tabMembers": "सदस्य", "tabActivity": "गतिविधि",
  "leaveGroup": "ग्रुप छोड़ें", "leaveGroupTitle": "यह ग्रुप छोड़ें?",
  "leaveGroupBody": "बाकी सदस्य आपका ऐप टेस्ट करना बंद कर देंगे और आपके ट्रस्ट पॉइंट कटेंगे। इसे वापस नहीं किया जा सकता।",
  "youWereRemoved": "आपको हटाया गया: {reason}।",
  "youCompleted": "आपने यह ग्रुप पूरा किया 🏆 अब आप Play Console में प्रोडक्शन एक्सेस के लिए आवेदन कर सकते हैं।",
  "setupDeadlinePassed": "सेटअप की समय-सीमा खत्म। प्रोसेस हो रहा है…",
  "setupTimeLeft": "सेटअप पूरा करने के लिए {hours}घं {minutes}मि बाकी",
  "setupExplain": "जो सदस्य पूरा नहीं करते, उनकी जगह कतार से लोग आते हैं। सब तैयार होने पर टेस्ट शुरू होता है।",
  "step1AddEmails": "चरण 1 · अपने क्लोज़्ड टेस्ट में टेस्टर जोड़ें",
  "addEmailsBody": "सभी {count} ईमेल कॉपी करें और Play Console में अपनी क्लोज़्ड टेस्टिंग ईमेल लिस्ट में पेस्ट करें।",
  "copyAllEmails": "सभी ईमेल कॉपी करें", "copied": "{count} ईमेल कॉपी हुए",
  "emailsConfirmed": "ईमेल जोड़े गए", "iAddedEveryone": "मैंने सबको जोड़ दिया",
  "confirmEmailsTitle": "क्या आपने सभी ईमेल जोड़ दिए?",
  "confirmEmailsBody": "पुष्टि करें कि सभी {count} ईमेल आपकी क्लोज़्ड टेस्ट की टेस्टर लिस्ट में हैं और बदलाव सेव हो गया है। अगर सदस्य जुड़ नहीं पाए तो वे आपकी रिपोर्ट कर सकते हैं।",
  "yesAdded": "हाँ, सब जोड़ दिए",
  "emailsHowTo": "Play Console → आपका ऐप → Testing → Closed testing → Testers → Email list → पेस्ट → Save।",
  "step2InstallApps": "चरण 2 · ऐप्स में जुड़ें और इंस्टॉल करें ({done}/{total})",
  "checkAgain": "फिर जांचें",
  "waitingForOwners": "{count} सदस्यों ने अभी ग्रुप के ईमेल नहीं जोड़े हैं। जोड़ने के बाद उनके ऐप यहां दिखेंगे।",
  "noAppsYet": "अभी इंस्टॉल करने के लिए कोई ऐप नहीं।", "byName": "{name} द्वारा", "joinTest": "टेस्ट में जुड़ें",
  "newMembersTitle": "नया सदस्य जुड़ा",
  "newMembersBody": "नए ईमेल अपने क्लोज़्ड टेस्ट में जोड़ें और उनका ऐप इंस्टॉल करें। सेटअप टैब खोलें।",
  "usageAccessOffTitle": "यूसेज एक्सेस बंद है",
  "usageAccessOffBody": "सिर्फ़ खोलें बटन से खोले गए ऐप गिने जाते हैं। होम स्क्रीन से खोलने पर भी क्रेडिट पाने के लिए यूसेज एक्सेस चालू करें।",
  "yourTestList": "आपकी टेस्ट सूची",
  "todayTitle": "आज की टेस्टिंग", "todayDone": "आज का सब पूरा 🎉", "todayDoneBody": "बढ़िया! कल फिर आइए।",
  "todayBody": "कम से कम {needed} ऐप खोलें और हर एक को थोड़ा इस्तेमाल करें।",
  "dayResetsAt": "नया दिन {time} बजे शुरू होता है",
  "notInstalled": "इंस्टॉल नहीं है", "openedMinutes": "आज खोला · {minutes} मिनट", "notOpenedYet": "आज नहीं खोला",
  "feedbackGivenCount": "फीडबैक ({count})", "giveFeedback": "फीडबैक",
  "statMembers": "सदस्य", "statOnTrack": "आज सही राह पर", "statRemoved": "हटाए गए",
  "membersLegend": "🟢 सही राह पर  🟡 अभी बाकी  🔴 दिन छूटे  ⚪ चले गए",
  "memberSetupLine": "ईमेल {emails} · इंस्टॉल {installed}/{total}",
  "memberActiveLine": "इंस्टॉल {installed}/{total} · खोले {opened}/{total} · फीडबैक {feedback}",
  "missedInARow": "लगातार {count} दिन छूटे",
  "lastDays": "पिछले दिन", "viewProfile": "प्रोफ़ाइल देखें", "openInPlay": "Play Store में खोलें", "reportMember": "रिपोर्ट करें",
  "reportSent": "रिपोर्ट भेजी गई। ग्रुप को निष्पक्ष रखने के लिए धन्यवाद।",
  "reportTitle": "{name} की रिपोर्ट करें",
  "reportExplain": "कार्रवाई तभी होती है जब कई सदस्य रिपोर्ट करें और हमारा यूसेज डेटा भी सहमत हो। झूठी रिपोर्ट पर ट्रस्ट पॉइंट कटते हैं।",
  "detailsOptional": "विवरण (वैकल्पिक)", "addScreenshot": "स्क्रीनशॉट जोड़ें", "screenshotAdded": "स्क्रीनशॉट जुड़ गया ✓",
  "sendReport": "रिपोर्ट भेजें", "noActivity": "अभी कोई गतिविधि नहीं",
  "evFormed": "{count} डेवलपर्स के साथ ग्रुप बना", "evJoined": "{name} ग्रुप में जुड़े",
  "evEmailsAdded": "{name} ने सबके ईमेल जोड़े", "evStarted": "टेस्टिंग शुरू: दिन 1",
  "evMemberActive": "{name} ने सेटअप पूरा करके टेस्टिंग शुरू की", "evWarning": "{name} लगातार 2 दिन चूके (आखिरी चेतावनी)",
  "evRemoved": "{name} को हटाया गया ({reason})", "evSuspended": "{name} एडमिन समीक्षा में हैं",
  "evReinstated": "{name} निर्दोष पाए गए और वापस आ गए", "evCompleted": "ग्रुप पूरा हुआ 🏆", "evCancelled": "ग्रुप रद्द हुआ",
  "feedbackSent": "फीडबैक भेजा गया। धन्यवाद!", "feedbackFor": "फीडबैक: {app}",
  "developerAsks": "डेवलपर आपसे यह आज़माने को कहते हैं", "rating": "रेटिंग", "category": "श्रेणी",
  "yourFeedback": "आपका फीडबैक",
  "feedbackHint": "क्या अच्छा चला, क्या टूटा, क्या उलझा? स्पष्ट लिखें: स्क्रीन, स्टेप, डिवाइस।",
  "feedbackMin": "कम से कम 20 अक्षर", "sendFeedback": "फीडबैक भेजें",
  "received": "मिले", "given": "दिए",
  "noFeedbackReceived": "अभी कोई फीडबैक नहीं", "noFeedbackReceivedBody": "आपके ग्रुप के टेस्टर्स का फीडबैक यहां दिखेगा।",
  "noFeedbackGiven": "आपने अभी फीडबैक नहीं दिया", "noFeedbackGivenBody": "ग्रुप के आज टैब में हर ऐप पर फीडबैक बटन इस्तेमाल करें।",
  "fromOnApp": "{name}, {app} पर", "wasHelpful": "क्या यह मददगार था?",
  "markedHelpful": "आपने इसे मददगार बताया (उन्हें +2 ट्रस्ट)", "markedNotHelpful": "मददगार नहीं बताया",
  "groupHistory": "ग्रुप", "noGroupsYet": "अभी कोई ग्रुप नहीं।",
  "trustHistory": "ट्रस्ट स्कोर इतिहास", "noTrustHistory": "अभी कोई बदलाव नहीं।",
  "trustScore": "ट्रस्ट स्कोर", "pointsToNext": "अगले लेवल के लिए {points} पॉइंट",
  "statCompleted": "पूरे ग्रुप", "statCompletionRate": "पूरा करने की दर", "statDailyActivity": "रोज़ की गतिविधि",
  "statActiveDays": "सक्रिय दिन", "statFeedback": "दिए फीडबैक", "statHelpful": "मददगार फीडबैक",
  "badges": "बैज", "noBadges": "बैज पाने के लिए अपना पहला ग्रुप पूरा करें।",
  "systemLanguage": "सिस्टम डिफ़ॉल्ट", "general": "सामान्य", "about": "जानकारी",
  "contactSupport": "सपोर्ट से संपर्क", "rateApp": "TestPact को रेट करें", "account": "अकाउंट",
  "deleteAccount": "अकाउंट हटाएं", "deleteAccountTitle": "अपना अकाउंट हटाएं?",
  "deleteAccountBody": "आपकी प्रोफ़ाइल, ऐप्स और ट्रस्ट स्कोर हमेशा के लिए हट जाएंगे। अगर आप किसी ग्रुप में हैं तो उससे हटा दिए जाएंगे।",
  "appealTitle": "किसी फैसले पर अपील करें",
  "appealExplain": "बताएं क्या हुआ। एडमिन हर अपील की समीक्षा करते हैं। स्वीकार होने पर एक स्ट्राइक हटता है और कुछ ट्रस्ट पॉइंट वापस मिलते हैं।",
  "appealHint": "क्या हुआ? तारीखें और जांच में मदद करने वाली कोई भी जानकारी लिखें।",
  "appealSent": "अपील भेजी गई", "sendAppeal": "अपील भेजें", "yourAppeals": "आपकी अपीलें",
  "appealOpen": "समीक्षा का इंतज़ार", "appealAccepted": "स्वीकार", "appealRejected": "अस्वीकार",
  "adminReviews": "समीक्षाएं", "adminAppeals": "अपीलें", "adminUsers": "यूज़र",
  "noteOptional": "यूज़र के लिए नोट (वैकल्पिक)", "nothingToReview": "समीक्षा के लिए कुछ नहीं 🎉",
  "dataSummary": "यूसेज डेटा: {active} सक्रिय दिन, {missed} छूटे दिन",
  "rejectReports": "रिपोर्ट खारिज करें", "confirmKick": "पुष्टि करें और हटाएं",
  "searchByEmail": "ईमेल से यूज़र खोजें", "userNotFound": "इस ईमेल का कोई यूज़र नहीं।",
  "userSummary": "ट्रस्ट {trust} · स्ट्राइक {strikes} · बैन: {banned}",
  "ban": "बैन करें", "unban": "बैन हटाएं", "adjustTrust": "ट्रस्ट स्कोर बदलें",

  "notificationsInbox": "नोटिफिकेशन", "markAllRead": "सभी पढ़े हुए करें",
  "noNotifications": "अभी कोई नोटिफिकेशन नहीं",
  "noNotificationsBody": "ग्रुप अपडेट, रिमाइंडर, चेतावनियां और फीडबैक अलर्ट यहां दिखेंगे।",
  "notificationSettings": "नोटिफिकेशन",
  "notifPermissionOff": "TestPact के लिए नोटिफिकेशन बंद हैं", "openSettings": "सेटिंग्स खोलें",
  "notifDaily": "रोज़ के रिमाइंडर",
  "notifDailySub": "अगर आज के ऐप नहीं खोले तो शाम को रिमाइंडर, और सेटअप की समय-सीमा",
  "notifGroup": "ग्रुप अपडेट", "notifGroupSub": "ग्रुप बना, टेस्ट शुरू, नए सदस्य, पूरा होना",
  "notifFeedback": "फीडबैक", "notifFeedbackSub": "जब कोई आपके ऐप पर फीडबैक दे",
  "notifImportantNote": "चेतावनियां और हटाए जाने की सूचना हमेशा भेजी जाती है, ताकि आपकी जगह से जुड़ी कोई बात न छूटे।",
  "noInternetTitle": "इंटरनेट कनेक्शन नहीं है",
  "noInternetBody": "अपना Wi-Fi या मोबाइल डेटा जांचें। ऑनलाइन होते ही TestPact अपने-आप जुड़ जाएगा।",
  "checkingConnection": "जांच रहे हैं…", "backOnline": "फिर से ऑनलाइन",
  "updateRequiredTitle": "अपडेट ज़रूरी है",
  "updateRequiredBody": "TestPact का यह वर्शन अब सपोर्टेड नहीं है। अपने ग्रुप के साथ टेस्टिंग जारी रखने के लिए अपडेट करें।",
  "updateAvailableTitle": "अपडेट उपलब्ध है",
  "updateAvailableBody": "TestPact का नया वर्शन सुधारों और फिक्स के साथ तैयार है।",
  "updateNow": "अभी अपडेट करें", "later": "बाद में",
  "updateDownloaded": "अपडेट डाउनलोड हो गया। इंस्टॉल पूरा करने के लिए रीस्टार्ट करें।", "restart": "रीस्टार्ट",
  "appVersion": "वर्शन {version}",

  "welcomeBack": "आपको फिर देखकर अच्छा लगा!", "viewAll": "सभी देखें", "more": "और",
  "filterAll": "सभी", "statusTesting": "टेस्टिंग", "inQueueShort": "कतार में", "statusReady": "तैयार",
  "memberDone": "पूरा", "memberTesting": "टेस्टिंग", "memberPending": "आज बाकी",
  "todaysTasks": "आज के काम",
  "tasksCompleted": "{total} ऐप · {done}/{total} पूरे",
  "groupMembersCount": "ग्रुप सदस्य ({count})",
  "recentActivity": "हाल की गतिविधि",
  "badgesEarned": "{total} में से {earned} मिले",
}
